name: shutterstock_scroll
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1
  cached_network_image: ^1.0.0
  flutter_cache_manager: ^1.0.0
  shimmer: ^1.0.0
  ansicolor: ^1.0.2
  fluttertoast: ^3.1.0

  mockito: ^4.1.0

  sentry: ^2.2.0
  
  flutter_launcher_icons: ^0.7.2+1

  connectivity: ^0.4.3+5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1

flutter_icons:
    android: "launcher_icon"  
    ios: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  
